name: metawrap-py3
channels:
  - conda-forge
  - bioconda
dependencies:
  - biopython
  - bwa
  - samtools
  - perl-bioperl
  - checkm-genome
  - concoct=1.0.0
  - maxbin2
  - metabat2
  - seaborn
  - numpy
  - matplotlib
  - spades
  - eukrep=0.6.7
  - scikit-learn=0.19.2
  - eukcc=2.1.0
